Fix nil exception when using open command
An "undefined method `to_sym' for nil:NilClass (NoMethodError)" was
raised when invoking "terminitor open <project>".
This happens because the options hash passed to 'edit' method by 'open'
doesn't have :syntax key.